export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS"
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS"

export const HANDLE_CHANGE = "HANDLE_CHANGE"

export const CHANGE_USERS_CHANGED = "CHANGE_USERS_CHANGED"

export const DISPLAY_ALERT = "DISPLAY_ALERT"
export const CLOSE_ALERT = "CLOSE_ALERT"

export const RESET_USER = "RESET_USER"